### ISSUE TITLE
[3pt][SPIKE] verify kebechet's advise manager is working on all overlays

### ISSUE THREAD

**Issue by goern** [thoth-station/ps-nlp#151] opened 2022-03-08 09:15 UTC
**High-level Goals**
verify kebechet's advise manager is working on all overlays

**Acceptance Criteria**

- [ ] all the overlay directories should have up to date Pipefile/Pipefile.lock based on Thoth's current production data.
- [ ] identify list of actions/issues if problems are present (like data is outdated, ...)

**Comment by codificat** [comment] 2022-05-05 11:56
A pre-requisite for this is https://github.com/thoth-station/core/issues/326

/sig user-experience
/triage accepted
/priority important-soon

**Comment by codificat** [comment] 2022-06-23 08:04
fixing duplicate priorities here:
/remove-priority important-soon

**Comment by harshad16** [comment] 2022-07-08 14:59
When `kebechet advise` is being triggered via issue.
the log shows:
```
2022-07-08 14:57:28,973   1 INFO     kebechet:196: Running manager 'thoth-advise' for 'thoth-station/ps-nlp'
2022-07-08 14:57:30,562   1 DEBUG    kebechet.managers.thoth_advise.thoth_advise:305: No issue found to start advises for.
```
[kebechet-job-220708145721-42be33530d896d11-980726572-main.log](https://github.com/thoth-station/ps-nlp/files/9073004/kebechet-job-220708145721-42be33530d896d11-980726572-main.log)


seems like it unable to find the issue in the repo #156 .
that seems to be the issue.

**Comment by harshad16** [comment] 2022-07-08 15:26
update seems like we need to use the case-sensetive title.
https://github.com/thoth-station/kebechet/blob/4b658e4f6ea36a7bed2e89c4efd6adc476685482/kebechet/managers/thoth_advise/thoth_advise.py#L62
 
 with the new issue: #157 
 it seems like the adviser work from issue.
 
maybe the issue is:
 - [ ] if the push event is allowed to trigger adviser.

**Comment by shreekarSS** [comment] 2022-07-08 19:14
While testing  creation of 'Kebechet Advise ' issue to get thamos advise,
 I faced this permission issue https://github.com/shreekarSS/ps-nlp/issues/6#issuecomment-1179241384
So I added myself as a owner to test and opened https://github.com/thoth-station/kebechet/pull/1081,  the way kebechet reading the it's own OWNER file than reading the OWNERS from cloned repo

**Comment by harshad16** [comment] 2022-07-11 15:14
The kebechet-run-result is able to process a little bit ahead
however it fail on resolving through the result of adviser.
issue: https://github.com/thoth-station/support/issues/244

**Comment by harshad16** [comment] 2022-07-11 15:38
Fixing this comment would fix the issue:
https://github.com/thoth-station/support/issues/244#issuecomment-1180565481

**Comment by harshad16** [comment] 2022-07-15 03:29
The kebechet thoth-advise is unable to parse the result and share the output a PR.
The reason is due to the formatting. As result of the thamos `get_analysis_results` is  a tuple with (result, error_boolean)
https://github.com/thoth-station/kebechet/blob/536cf1ca02c933e11c1f5ddea0a3d659964f955b/kebechet/managers/thoth_advise/thoth_advise.py#L390
The result formatting needs to be rechecked.

Tasks to do:
- [ ] Familiarize through kebechet [thoth-advise](https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/thoth_advise/thoth_advise.py) code base and thamos `[lib](https://github.com/thoth-station/thamos/blob/master/thamos/lib.py)`  code base.
- [ ] Figure out what formatting is out of order and where all to change source code, to fit to the latest thamos.
- [ ] Update kebechet thoth-advise code base with suitable changes.
- [ ]  **If changes**, are required on thamos end, open a issue in thamos with proper details and proposal.
   - [ ] work on creating the thamos end source code.
- [ ] Open PR for review

The process to test in local:
The focus part is kebechet output retrieved from adviser, which is handled by `kebechet [run-result](https://github.com/thoth-station/kebechet/blob/536cf1ca02c933e11c1f5ddea0a3d659964f955b/kebechet/cli.py#L108)`

Required params example:
```
KEBECHET_REPO_URL = "https://github.com/thoth-station/ps-nlp"
KEBECHET_SERVICE_NAME= "github"
KEBECHET_ANALYSIS_ID = "adviser-220715024124-598c498944fcb667"
THOTH_ADVISER_METADATA="{"origin": "https://github.com/thoth-station/ps-nlp", "re_run_adviser_id": null, "source_type": "KEBECHET", "kebechet_metadata": null, "thoth.adviser": {"justification": null, "stack_info": null}}"
```
Follow a similar pattern and try out different analysis id while working on this.
Different analysis ids can be found here in comments: https://github.com/thoth-station/ps-nlp/issues/160

**Comment by shreekarSS** [comment] 2022-07-18 18:04
FYI https://github.com/thoth-station/kebechet/issues/1094

**Closed** 2022-07-19 15:56 UTC
Labels: kind/feature, sig/user-experience, priority/critical-urgent, triage/accepted
